name: Run benchmarks on PR
on:
  pull_request:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install asv
        run: pip install -U pip virtualenv asv
      - name: Fetch base branch
        run: |
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
          git fetch origin $GITHUB_HEAD_REF:$GITHUB_HEAD_REF
      - name: Run benchmarks
        run: |
          asv machine --machine "GitHubRunner"
          # Get IDs of branch and PR commits
          BASE_COMMIT=$(git rev-parse $GITHUB_BASE_REF)
          HEAD_COMMIT=$(git rev-parse $GITHUB_HEAD_REF)
          echo $BASE_COMMIT | tee commits_to_compare.txt
          echo $HEAD_COMMIT | tee -a commits_to_compare.txt
          asv run HASHFILE:commits_to_compare.txt --m "GitHubRunner" --show-stderr
      - name: Compare commits' benchmark results
        run: |
          cat commits_to_compare.txt
          BASE_COMMIT=$(head -1 commits_to_compare.txt)
          HEAD_COMMIT=$(tail -1 commits_to_compare.txt)
          asv compare $BASE_COMMIT $HEAD_COMMIT


    
